version: 0.0
os: linux
files:
  - source: src
    destination: /webapps/dbhelpers/src
  - source: oneoff
    destination: /webapps/dbhelpers/oneoff
  - source: requirements.txt
    destination: /webapps/dbhelpers
  - source: scripts
    destination: /webapps/dbhelpers/scripts
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
  AfterInstall:
    - location:  scripts/after_install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
